### PR TITLE
Update to 1.0.0

### LINKED ISSUE #1: V remake
As the title suggest, remake vroom in V as a fully featured V frontend

### PR DESCRIPTION
**Pull request by malisipi**
CHANGELOG:
- Rewrite in V ( It fixes #1 )
- Make a GUI
- Support smaller (~33%) executables
- Support complex applications (ex. applications that uses gg module)
- Support compiling VRoom itself.

TODO:
- Make better command line interface
  * Add -cc flag
  * Add -strip flag
  * Add -compress flag
  * Add -cflags flag

### CODE REVIEW

**Comment by SheatNoisette** [comment]
Thanks for your contribution!

However, I would prefer to avoid using a external library for argument parsing as V already ship that.

~ SheatNoisette

**Comment by malisipi** [comment]
I didn't use external library for argument parsing. There are one external module that i use. And it's for GUI, not argument parsing.

**Comment by SheatNoisette** [comment]
My bad, but why making a TUI interface in this instance ?

**Comment by malisipi** [comment]
It has command line interface but options that placed in to-do section, is missing. If you don't pass argument, it starts gui. If you pass arguments, it compiles the program without starting gui.

**Comment by malisipi** [comment]
I was misunderstand you. I was understand you are talking about CLI with saying TUI.

I think GUI is better than TUI, if you have CLI. Also maintaining is much easier with using pre-created widgets. TUI is not have basic windowing system, dialogs (especially file dialogs) and widgets. And a GUI has all of that.

**Pull request closed without merging**
